### PR TITLE
Ignore *.plist and *.skel.legacy.h files

### PR DESCRIPTION
**Pull request by Rtoax**

### CODE REVIEW

**Comment by alan-maguire** [comment]
change looks good, thanks! Currently the check for the Oracle Contributor Agreement is failing - instructions for OCA application are above and in https://github.com/oracle/bpftune/blob/main/CONTRIBUTING.md . If you complete that process, can you add a note here so I can see if the checks get updated correctly? Thanks!

**Comment by Rtoax** [comment]
> change looks good, thanks! Currently the check for the Oracle Contributor Agreement is failing - instructions for OCA application are above and in https://github.com/oracle/bpftune/blob/main/CONTRIBUTING.md . If you complete that process, can you add a note here so I can see if the checks get updated correctly? Thanks!

I don't know why, i already signed the OCA, however, stuck on `Oracle Contributor Agreement` still. please help.

**Comment by Rtoax** [comment]
> change looks good, thanks! Currently the check for the Oracle Contributor Agreement is failing - instructions for OCA application are above and in https://github.com/oracle/bpftune/blob/main/CONTRIBUTING.md . If you complete that process, can you add a note here so I can see if the checks get updated correctly? Thanks!

Shows 

```
Warning:
You cannot submit a new request unless the one that is under review is approved or rejected.
```

**Comment by alan-maguire** [comment]
i've rerun checks and they still fail; possible the approval is still pending. i don't yet see you on the list at https://oca.opensource.oracle.com/?ojr=contrib-list so it's possible it just takes a few days to show up. i'll follow up with opensource admins on monday if still not working then..

**Comment by alan-maguire** [comment]
Asked the admin folks; they said the OCA request was rejected because the full mailing address was not specified. Could you submit a new OCA request, making sure to match the email used in the OCA request and the pull request? thanks!

**Comment by Rtoax** [comment]
> Asked the admin folks; they said the OCA request was rejected because the full mailing address was not specified. Could you submit a new OCA request, making sure to match the email used in the OCA request and the pull request? thanks!

I just signed OCA again, please review. thanks.

**Pull request merged**
